FROM node:latest

WORKDIR /home/node/app

RUN chown node:node /home/node/app

USER node

COPY --chown=node:node package.json package-lock.json /home/node/app

RUN npm i

COPY server.js /home/node/app

CMD ["npm", "start"]
#["node", "/home/node/app/server.js"]

